### ISSUE TITLE
sqlalchemy error

### ISSUE THREAD

**Issue by kalebbroo** [Hydro74000/Monocle#17]
New to this but I have used the original monocle in the past. Not able to get db setup so I can run the map.
`kaleb@kaleb-HP-Pavilion-g4-Notebook-PC:~/Desktop/Hydra-Monocle/Monocle$ alembic upgrade head
Traceback (most recent call last):
  File "/home/kaleb/.local/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/home/kaleb/.local/lib/python3.5/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/kaleb/.local/lib/python3.5/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/home/kaleb/.local/lib/python3.5/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/home/kaleb/.local/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/kaleb/.local/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/kaleb/.local/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/kaleb/.local/lib/python3.5/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 11, in <module>
    from monocle import sanitized as conf, db as db, accounts
  File "/home/kaleb/Desktop/Hydra-Monocle/Monocle/monocle/db.py", line 331, in <module>
    _engine = create_engine(conf.DB_ENGINE, pool_size=conf.DB_POOL_SIZE, max_overflow=conf.DB_MAX_OVERFLOW, pool_recycle=conf.DB_POOL_RECYCLE, isolation_level='READ_UNCOMMITTED')
  File "/home/kaleb/.local/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 391, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/kaleb/.local/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 160, in create
    engineclass.__name__))
TypeError: Invalid argument(s) 'pool_size','max_overflow' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
kaleb@kaleb-HP-Pavilion-g4-Notebook-PC:~/Desktop/Hydra-Monocle/Monocle$ 
`

**Comment by Hydro74000** [comment]
What is your sqlalchemy version ?

**Comment by kalebbroo** [comment]
1.1.15

**Comment by Hydro74000** [comment]
Did you install the optionnal requierements ?
If you did, try :

pip3 install mysqlclient>=1.3

Also, come in discord, support will be faster :-)

**Comment by ZouHuaYi** [comment]
sqlalchemy msyq Columnl why can not set default

**Comment by Hydro74000** [comment]
Closing issue - project is over
